### ISSUE TITLE
Follow Up?

### ISSUE THREAD

**Issue by SAMFYB** [LyricLy/IdlePY#1]
Hi,

Are you still maintaining this? Your project came up top of Google search "terminal idle games". Looks like you've stopped working on it. Would you include some documentation? I'd love to try it.

Thanks,
Sam

**Comment by LyricLy** [comment]
I stopped maintaining this since I have no new ideas for it, however you can still play it. I've just pushed some changes that I made a while ago but forgot to push. Just download [the latest release](https://github.com/LyricLy/IdlePY/releases/tag/v0.3-alpha) and run `main.py` in Python 3.6.

**Comment by SAMFYB** [comment]
Great Thx
