### ISSUE TITLE
Bug, game crashes

### ISSUE THREAD

**Issue by JonatanSchnyder** [LyricLy/IdlePY#2]
I tested the game and found a bug relatively early in the beginning of the game.

After adding 20 points to your points, the following prompt comes:

    You have a new update available to the operating system!
    Use the 'update' command to update your system.

<br>
When you now use the command save, the program crashes

<br><br>
my bash output:

    /shell>points
    You have 19 points.
    /shell>add
    Added 1 point.
    You have a new update available to the operating system!
    Use the 'update' command to update your system.
    /shell>buy
    Invalid command.
    /shell>add
    Added 1 point.
    /shell>save
    Traceback (most recent call last):
      File "/redacted/IdlePY/commands_logic.py", line 20, in next_command
        function(*arguments)
      File "/redacted/IdlePY/commands/core_commands.py", line 56, in save
        f.write(base64.b64encode(json.dumps(save).encode('utf-8')).decode('utf-8'))
                                 ^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/__init__.py", line 231, in dumps
        return _default_encoder.encode(obj)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/encoder.py", line 200, in encode
        chunks = self.iterencode(o, _one_shot=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/encoder.py", line 258, in iterencode
        return _iterencode(o, 0)
               ^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/json/encoder.py", line 180, in default
        raise TypeError(f'Object of type {o.__class__.__name__} '
    TypeError: Object of type function is not JSON serializable
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/redacted/IdlePY/main.py", line 27, in <module>
        commands_logic.next_command()
      File "/redacted/IdlePY/commands_logic.py", line 23, in next_command
        print("Invalid usage. '{0}' takes {1} arguments but {2} were given. Use 'help {0}' for usage     instructions.".format(function.__name__, error[0], error[1]))
                                                                                                                                              ~~~~~^^^
    IndexError: list index out of range


I think the second Traceback is more important for this case,

By the Way: a new but emtpy save.json is created

**Comment by LyricLy** [comment]
Enjoy the game! All 2 minutes of playtime it has.
